feeder: dataset.dataloader_video.BaseFeeder
phase: train
dataset: phoenix2014
num_epoch: 40
work_dir: ./work_dir/test/
batch_size: 2
random_seed: 0
test_batch_size: 2
num_worker: 4
device: 0
log_interval: 10000
eval_interval: 1
save_interval: 5
# python in default
evaluate_tool: python
loss_weights:
  SeqCTC: 1.0
  ConvCTC: 1.0
  ConvExtraCTC: 1.0
  Dist: 25.0
  DistExtra: 25.0
  Cp: 0.001
  Cu: 0.001

optimizer_args:
  optimizer: Adam
  base_lr: 0.0001
  scheduler: multistep
  step: [20, 25, 30, 35]
  learning_ratio: 1
  gamma: 0.2
  weight_decay: 0.0001
  start_epoch: 0
  nesterov: False

feeder_args:
  mode: 'train'
  datatype: 'video'
  num_gloss: -1
  drop_ratio: 1.0
  frame_interval: 1
  image_scale: 1.0  # 0-1 represents ratio, >1 represents absolute value
  input_size: 224

model: slr_network.SLRModel
slowfast_config: SLOWFAST_64x2_R101_50_50.yaml
decode_mode: beam
model_args:
  num_classes: 1296
  c2d_type: swinad_bilstm

  conv_type: 2
  use_bn: 1
  share_classifier: 1
  weight_norm: True
